name: Docs

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install
      run: npm install

    - name: Build
      run: npm run doc

    - name: Publish
      if: github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.HYDROFRAME_BOT_TOKEN }}
      run: ./scripts/github-actions/publish_docs.sh
